server.port: 8081

spring:
  application:
    name: "order-service"
  jpa:
    database: POSTGRESQL
    open-in-view: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
  sql:
    init:
      platform: postgresql
      mode: embedded
  datasource:
    url: jdbc:postgresql://localhost:5432/pizza_db
    username: local
    password: "{cipher}e37e7ff7fbb2a5bc0b27fdbc39132eb1479465cb0e7f75737f7240873b072888"
  artemis:
    user: artemis
    password: "{cipher}64c46053ad698cc3297b0c03755aded5c74b4cf53ff1b7e7617bbecce1f439d7"

logging.level.com.learners: debug

app.config:
  default-page: 0
  default-size: 50
  pizza-service-host: "http://localhost:8080"
  pizza-service-path: "/api/v1/pizza/"
  validate-order-queue: "validate-order"
  validation-result-queue: "validation-result"
  allocate-order-queue: "allocate-order"
  allocation-result-queue: "allocation-result"
  deallocate-order-queue: "deallocate-order"
  allocation-error-queue: "allocation-error"
